name       : dpkg
version    : 1.18.24
release    : 9
source     :
    - http://ftp.debian.org/debian/pool/main/d/dpkg/dpkg_1.18.24.tar.xz : d853081d3e06bfd46a227056e591f094e42e78fa8a5793b0093bad30b710d7b4
license    : GPL-2.0
summary    : DO NOT USE THIS?!?!?!?!?!?
component  : programming.devel
description: |
    Debian Package Manager - for Cross Distro Purposes. Do NOT use to
    attempt installation of packages on Solus, it's not compatible!!!
builddeps  :
    - bzip2-devel
setup      : |
    %configure --disable-start-stop-daemon \
               --disable-install-info \
               --disable-static
build      : |
    %make
install    : |
    %make_install
