name       : dpkg
version    : 1.18.4
release    : 5
source     :
    - http://ftp.debian.org/debian/pool/main/d/dpkg/dpkg_1.18.4.tar.xz : fe89243868888ce715bf45861f26264f767d4e4dbd0d6f1a26ce60bbbbf106da
license    : GPL-2.0
summary    : Debian Package Manager - For XDistro purposes
component  : programming.devel
description: |
    Debian Package Manager - for Cross Distro Purposes. Do NOT use to
    attempt installation of packages on Solus, it's not compatible!!!
setup      : |
    %configure --disable-start-stop-daemon \
               --disable-install-info \
               --disable-static
build      : |
    %make
install    : |
    %make_install
