name       : dpkg
version    : 1.21.22
release    : 18
source     :
    - https://ftp.debian.org/debian/pool/main/d/dpkg/dpkg_1.21.22.tar.xz : 5a1d15481bba79d7a4899fd55b4b6b18a987ca8d56ee8c43e9cab63b8a0a3545
license    : GPL-2.0-or-later
component  : programming.devel
homepage   : https://wiki.debian.org/dpkg/
summary    : DO NOT USE THIS.
description: |
    Debian Package Manager - for Cross Distro Purposes. Do NOT use to attempt installation of packages on Solus, it's not compatible!
builddeps  :
    - pkgconfig(bzip2)
    - pkgconfig(liblzma)
    - pkgconfig(libmd)
rundeps    :
    - perl
setup      : |
    %configure \
        --disable-start-stop-daemon \
        --disable-install-info \
        --disable-static
build      : |
    %make
install    : |
    %make_install

    # use standard names for man pages
    for file in $installdir/usr/share/man/man3/*; do
        newname=$(echo "$file" | sed -Ee 's/3perl/3/')
        mv "$file" "$newname"
    done

    # nuke docs
    rm -rf $installdir/usr/share/doc

    # why is this even here
    rm -f $installdir/etc/alternatives/README

    # delete empty dirs
    find $installdir -type d -empty -delete
