name       : dpkg
version    : 1.18.18
release    : 7
source     :
    - http://ftp.debian.org/debian/pool/main/d/dpkg/dpkg_1.18.18.tar.xz : c88b61e3d4660500753142689e8ddbeff1c731f29549f3338e6975f655936ff5
license    : GPL-2.0
summary    : DO NOT USE THIS?!?!?!?!?!?
component  : programming.devel
description: |
    Debian Package Manager - for Cross Distro Purposes. Do NOT use to
    attempt installation of packages on Solus, it's not compatible!!!
setup      : |
    %configure --disable-start-stop-daemon \
               --disable-install-info \
               --disable-static
build      : |
    %make
install    : |
    %make_install
